### ISSUE TITLE
reset the entered value

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform-bs-datepicker#10]
unless the new form submit with error of any other input

**Comment by comerc** [comment]
Also you can see this bug [here](http://autoform-bs-more.meteor.com/)

**Comment by poojabansal** [comment]
+1

**Comment by comerc** [comment]
Not only for meteor-autoform-bs-datepicker, it is common problem for ss-type: Date

(Chrome+Ubuntu)

**Comment by lugaru90** [comment]
+1

To describe the Problem a bit more specific: When you submit the form, and there is an validation Error, the value you have entered is removed!

Also data-date-language='de' is not working as it seems.

**Comment by comerc** [comment]
You may use https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/7

It works!

**Comment by lugaru90** [comment]
@comerc Still the same Problem, on first submit the value will be deleted and the error appears (required)

**Comment by comerc** [comment]
Hmm, I dont see this bug with my reproduction.

**Comment by lugaru90** [comment]
I've created a Repo for you, if you want to test it:
https://github.com/lugaru90/BugDemo

**Comment by comerc** [comment]
I need .meteor/packages

**Comment by lugaru90** [comment]
Sorry, fixed!

**Comment by comerc** [comment]
packages:
```
# tsega:bootstrap3-datetimepicker
```
console:
```
$ cd packages
$ git clone https://github.com/comerc/meteor-autoform-bs-datetimepicker.git
$ git checkout v4beta
```
It works!

**Comment by buduguru** [comment]
I'm experiencing the same problem, but not connected to validation:

1. in a schema I have an array of objects.
2. in each object there is a bootstrap-datepicker field
3. in a form if I choose a date in the first object and then add another object (click on plus button) then the date field in the first object is reset, so I need to choose a date again.

**Comment by buduguru** [comment]
Solved it by removing reactivity in autoform-bs-datepicker.js (this.autorun). Not the best fix if reactivity is needed. And have no idea why the bug is based on reactivity....

**Comment by nicodinh** [comment]
if you use only `type: Date` schema keys
juste remove  :
```javascript
else if (typeof data.value === "string") {
      $input.datepicker('update', data.value);
}
```

**Comment by pozylon** [comment]
+1

@nicodinh: it has been a long time since aldeed maintained the project.
 there a 2 more forks which fix critical errors (lgollut & nspangler), maybe you can pull those changes into your branch and deploy it to atmosphere so we all can stop use local packages? if nobody does it I will do end of next week.

**Comment by mbabauer** [comment]
@pozylon: Did you ever do the PR?  Debating if I should fork my own to fix, switch to one of the other mentioned packages, or just wait till the official package is working.

**Comment by pozylon** [comment]
@mbabauer i was too lazy and just used the fork of @lgollut. I downloaded his fork as a zip and copied the source into packages/

**Comment by mbabauer** [comment]
@pozylon I can totally understand that feeling.  Thanks for responding quickly.

**Comment by Shogutora** [comment]
+1

This is really rather annoying as it works fine otherwise.. I am using type: Date and in my form I have 2 dates from which the first one gets reset if the form validation fails.

However, if I enter it again and then submit, it stays fine.

**Comment by c316** [comment]
+1 same issue as @alexedev

**Comment by TimoRuetten** [comment]
@aldeed 's packages for meteor are mostly not maintained anymore. It makes no sense to write issues - best would be to create new packages instead.

**Comment by c316** [comment]
Got any recommendations for a good fork of this package?

**Comment by TimoRuetten** [comment]
I dont know a good one for the BS date / datetime picker. I will create a new one for my project and will publish it. Dont know if this or next week

**Comment by aldeed** [comment]
Closing old issues. Probably fixed in latest. Can be reopened if it's still an issue in the latest release.
