### ISSUE TITLE
don't work for popup form.

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform-bs-datepicker#13]
I use autoform on popup (bootbox), it don't work.
pl help me.

**Comment by comerc** [comment]
You may use https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/7

It works!

**Comment by yuomtheara** [comment]
it is work fine for datetimepicker on bootbox, but don't work for set default value.

**Comment by comerc** [comment]
need reproduction

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
