### ISSUE TITLE
Reactively setting minDate of a datepicker based on the value of another

### ISSUE THREAD

**Issue by coniel** [aldeed/meteor-autoform-bs-datepicker#14]
I need a pair of date inputs to select a date range. The end date should obviously be after the start date.  I can validate that using a custom validation method, but how would I go about making the minDate of the end date field be equal to the value of the start date field?

I tried the following, but it doesn't work (I get: Object #<Object> has no method 'field'), I guess the "field" method is only available in the custom validation function.

``` javascript
afFieldInput: {
    datePickerOptions: {
        minDate: this.field('startDate').value
    }
}
```

**Comment by chompomonim** [comment]
+1

**Comment by tylercreller** [comment]
Agreed!

**Comment by twk7890** [comment]
you can set the min value with the original.

xxx{
type:date,
min: new Date(moment().add(1, 'days').startOf('day')),
}
or just use min:new Date()

however, there still display today for selection but alert for choosing

**Comment by Murukaen** [comment]
+1

**Comment by aldeed** [comment]
Closing old issues. This could probably be done using a `min` helper in the template, based on reactive `AutoForm.getFieldValue` on the start field.
