### ISSUE TITLE
Required validation triggers on empty form

### ISSUE THREAD

**Issue by n-campos** [aldeed/meteor-autoform-bs-datepicker#15]
Hi, I have a simple schema with some String properties and a Date type property like: myDate: { type: Date } which are all required.
When I load my form, this property is the only one invalid from start if I don't give it an initial value, and it shows the "My date is required" label, as well as marking the field with the "error" class.

I've tried using both afQuickField and afFieldInput setting the type, but the result is the same. Any suggestions?

Thank you,
Nelson Campos

![image](https://cloud.githubusercontent.com/assets/7944661/6185900/2b6bcf24-b37c-11e4-8959-6707c90d7c45.png)

**Comment by aldeed** [comment]
Can you provide a minimal reproduction app?

**Comment by gtg092x** [comment]
I'm having this issue as well. Was there any work done here?

**Comment by gtg092x** [comment]
This might make things really easy:
https://github.com/aldeed/meteor-autoform-bs-datepicker/blob/master/autoform-bs-datepicker.js#L64

This line has the field getting updated (and validated). We're working around this by setting our default values to 0. The way to fix this is to do an empty string check before any initial validation.

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
