### ISSUE TITLE
$.datepicker[(("_" + options) + "Datepicker")] is undefined

### ISSUE THREAD

**Issue by nanu-c** [aldeed/meteor-autoform-bs-datepicker#18]
I use the datepicker multiple times and it seems like its only working the first time i am on my site and its happening when i try to submit a form.

```
TypeError: $.datepicker[(("_" + options) + "Datepicker")] is undefined
```

my schema looks like

```
    date: {
        type: String,
        label: "When did it happen?",
        index: 7,
        optional: false,
        autoform: {
            afFieldInput: {
                type: "bootstrap-datepicker",
                datePickerOptions: function () {
                    return {
                      autoclose: true
                    }

                }
            }
        }
    },
```

and my autoform-part

```
 {{> afFormGroup name="date" type="bootstrap-datepicker" }}
```

the whole code is in my desaparecidos-repro [here](https://github.com/moxor/desaparecidos).
Would be nice to get some hint.

![datetimepicker error](https://cloud.githubusercontent.com/assets/404058/6911876/da13f626-d723-11e4-8cbe-837e29ee576d.png)
(Also the glyphons aren't working, but thats another case)

**Comment by juliomac** [comment]
This works on my code: 

  Date: {
    label: function() {
        return(TAPi18n.__('Date'));
      },
    type: Date,
    autoform: {
     afFieldInput: {
        type: "bootstrap-datepicker",
        datePickerOptions: {
        	autoclose: true,
        	language: 'es'
  		}
      }
    }
  }

I guess the difference is that I don't use function as a way to add the options.
