### ISSUE TITLE
Compatible with autoform v5.1.x?

### ISSUE THREAD

**Issue by jfols** [aldeed/meteor-autoform-bs-datepicker#19]
Current version of bs-datepicker is restrained to autoform v5.0.0, tested with autoform v.5.1.2 and everything appears to work.

**Comment by aldeed** [comment]
It should work, but I haven't tested even with 5.0 yet. It depends on 5.0+, so you can update to any 5.x.x.

**Comment by jfols** [comment]
I received the following response when upgrading from autoform 4.2.2 to 5.1.2

```sh
meteor add aldeed:autoform@5.1.2                                                                                                            
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: aldeed:autoform 5.1.2, was 4.2.2.
Constraints on package "aldeed:autoform":
* aldeed:autoform@5.1.2 <- top level
* aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datepicker 1.1.1
```
So I then I ran
```sh
meteor update --allow-incompatible-update                                                                                                    ⏎
This project is already at Meteor 1.1, the latest release.

Changes to your project's package version selections from updating package versions:

aldeed:autoform*  upgraded from 4.2.2 to 5.1.2


* These packages have been updated to new versions that are not backwards
compatible.
```
So everything does appear to work, but the dependency is currently 5.0.x and not 5.x?

**Comment by jfols** [comment]
Perhaps I'm just reading the constraints messages incorrectly?

**Comment by aldeed** [comment]
`4.0.0 || 5.0.0` means `4.x.x or 5.x.x`, so there shouldn't be any conflict. Looks like you are on Meteor 1.1, which has a new constraint solver I think, so maybe a bug in that? I haven't updated anything to 1.1 yet.

**Comment by aldeed** [comment]
My money is on a bug in Meteor 1.1. I'd suggest submitting your issue in the meteor repo. Seems like there's some problem with that new `--allow-incompatible-update` flag where it's requiring that and ignoring the fact that multiple dependency versions are listed.

**Comment by jfols** [comment]
I should have read the release notes closer...
"Don't downgrade packages listed in .meteor/packages, or upgrade to a new major version, unless the new flag --allow-incompatible-update is passed as an override."
https://github.com/meteor/meteor/blob/devel/History.md#version-solver

So it's not datepicker package, just the fact that I was going from 4.x to 5.x.

**Comment by aldeed** [comment]
OK, I see, yeah if you were on 4.x when you tried the update I guess you need the flag. Not the most descriptive error message.
