### ISSUE TITLE
Which datePickerOptions are implemented?

### ISSUE THREAD

**Issue by juliomac** [aldeed/meteor-autoform-bs-datepicker#21]
I have been trying to localize the DatePicker with no success. I understand this is an implementation of bootstrap-datepicker for Meteor, so it might both have all the features of the former. Maybe it is just a silly mistake, but I tried everything I think of. I have included both rzymek:moment-locale-pt-br and rzymek:moment-locale-ex packages to no avail.

Below is my schema. I also tested some other options as shown on https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#clearbtn that did not have any effect either. Am I missing anything? Is there any other package that must be included for them to work or is it just no implemented?

  initialdate: {
    label: function() {
        return(TAPi18n.__('Check-in'));
      },
    type: Date,
    autoform: {
     afFieldInput: {
        type: "bootstrap-datepicker",
        datePickerOptions: {
        	language: 'es',                                        // No effect
        	autoclose: true,
     //   	todayBtn: true,						// No effect
     //		language: 'pt-BR',					// No effect
     //		locale: 'pt-BR',					        // No effect
     //		locale: moment.locale('pt-BR'),		// No effect
     //         daysOfWeekHighlighted: [0,6],		// No effect
     //		dayViewHeaderFormat: 'MMMM',
     		format: 'dd-mm-yyyy',  
     //		viewMode: 'months',
     //		toolbarPlacement: 'top',
     //		showTodayButton: true,
     //   	maxViewMode: 2, "years",		// Crash! How to use with comma???
     		calendarWeeks: true,
     		clearBtn: true, 
        	todayHighlight: true,
        	startDate: today(),
     	  	endDate: "31-12-2016"
  		}
      }
    }
  },

**Comment by shactdeveloper** [comment]
I can't change the language too.. also trying to set to 'pt-BR' ^^

**Comment by juliomac** [comment]
Well, I end up changing to https://github.com/rajit/bootstrap3-datepicker/ .

Rajit's excellent support even gave birth to the ```rajit:bootstrap3-datepicker-pt-br``` package to accompany the core one and translate accordingly. It is also available in other languages,
