### ISSUE TITLE
Problems with date update with autosave=true and bootstrap-datepicker

### ISSUE THREAD

**Issue by i-Hun** [aldeed/meteor-autoform-bs-datepicker#23]
You can see it on gif.
![Image](http://habrastorage.org/files/2cc/bff/a50/2ccbffa5046b4892ae09d26519d87680.gif)
With autosave=false everything works

**Comment by i-Hun** [comment]
I know you like minimal reproduction apps so
https://github.com/i-Hun/autoform-bs-datepicker-bug

**Comment by i-Hun** [comment]
now it works for me, but it not solves real problem
https://github.com/i-Hun/meteor-autoform-bs-datepicker/commit/a5ae4d8120ebaf9c01376fe97a6de519a21776a9

**Comment by bjimdar** [comment]
Yea, I ran into this same bug. 
If you use bootstrap-datepicker on a form with autosave=true,  you get stuck in an update loop that runs until the browser crashes.

**Comment by lynchem** [comment]
+1 - Very frustrating bug in an otherwise wonderful package

**Comment by mvgalle** [comment]
Having the same problem also. I tried to implement a fix similar to the one @aldeed posted about for the datetimepicker here: https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/3#issuecomment-74887495 (but using the datepicker) and was not successful. Has anyone implemented a workaround for this problem?

**Comment by timjong93** [comment]
+1 - Has anyone found a solution yet?

**Comment by aldeed** [comment]
Should be fixed in latest release

**Comment by bjimdar** [comment]
Confirmed. Way to follow through Eric!

**Comment by aldeed** [comment]
Better late than never...
