### ISSUE TITLE
Validation error for second date field on form load

### ISSUE THREAD

**Issue by poojabansal** [aldeed/meteor-autoform-bs-datepicker#25]
I am having a strange issue of seeing a required validation error for the second date field in a schema on form load.
I've created a small repo to reproduce the issue:
https://github.com/poojabansal/MultipleDates
And, here is a screenshot: http://cl.ly/image/2M213M3Y1H0T

**Comment by poojabansal** [comment]
Few more observations:
- I don't see the validation error if I remove `type: "bootstrap-datepicker"` for both or one of the date fields.
- I get the same validation error if I use https://github.com/aldeed/meteor-autoform-bs-datetimepicker package and specify type as `bootstrap-datetimepicker`.

**Comment by aldeed** [comment]
Should be fixed in latest release
