### ISSUE TITLE
Datepicker a day behind

### ISSUE THREAD

**Issue by joerodrig** [aldeed/meteor-autoform-bs-datepicker#28]
Ie. 
If I choose June 13th as a date, the date is actually input as June 12th. 

This causes some issues with setting a min date using " new Date()" in a collection as that generates the current day

**Comment by nspangler** [comment]
@joerodrig3 I was able to fix the issue in my case by the following change for the millisecond or "NUMBER"  date type. 

https://github.com/aldeed/meteor-autoform-bs-datepicker/compare/master...nspangler:patch-1

**Comment by aldeed** [comment]
Dates are UTC. Make sure you take that into account wherever you display them.
