### ISSUE TITLE
datePickerOptions

### ISSUE THREAD

**Issue by cutemachine** [aldeed/meteor-autoform-bs-datepicker#3]
I have problems setting the options for the date picker. I tried this, but it does not work.

```
birthday: {
  type: Date,
  autoform: {
    type: "bootstrap-datepicker",
    datePickerOptions: function () {
      return {
          autoclose: true
      }
    }
  }
}
```

Can you please point me in the right direction to pass in the options to the date picker component?

PS: Thanks for your great work on Collections, AutoForm, SimpleSchema and ...

**Comment by juliomac** [comment]
Thanks!

**Comment by gregory** [comment]
My workaround was to JSON.stringify the content and JSON.parse it to retrieve it
