### ISSUE TITLE
Global configuration options?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-autoform-bs-datepicker#30]
How do we configure the datepicker? E.g. I would like to highlight the current date. Is there a recommended way to configure the global options for the bootstrap datepicker?

**Comment by tbbooher** [comment]
+1 i can't get basic options to take:

```
Template.entry_form.onRendered ->
  $("#entry_date_id").datepicker
    orientation: "top left"
```

**Comment by gentunian** [comment]
Same here. Can't set orientation and "auto" seems to not work reliably inside dialogs.

**Comment by gentunian** [comment]
Well, I've found [this](https://github.com/jimmiebtlr/meteor-autoform-bs-datepicker/commit/771a354c501c0b0b60595cfbad23966ee6dc45bf) but can't set `orientation` there. Works for `autoclose` though.

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
