### ISSUE TITLE
When saving form the datepicker shows temporarily the original date

### ISSUE THREAD

**Issue by leolara** [aldeed/meteor-autoform-bs-datepicker#32]
I have a datepicker in the form, and I change the date date to a new one, then I click save, the user sees how the datepicker field date changes to the previous date temporarily until the form is saved and the user is redirected to another url.

The new date is saved correctly , but the user sees the old one for a second, so the user thinks the new date has not been saved.

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
