### ISSUE TITLE
no value storage of multiple datetpicker

### ISSUE THREAD

**Issue by devarashetty** [aldeed/meteor-autoform-bs-datepicker#38]
unable to store date picker as array , here is an example of schema which I am trying to implement , but when I click on addon/removeoff  button the value is changed back to empty, 
var schema=new SimpleSchema({
`'certification':{
    type: [Object],
    optional: true,
    label: "certification",
  },
'certification.$.expiredDate':{
    type: Date,
    label: "Certification Renewal Date",
    optional:true,
    autoform: {
      afFieldInput: {
        type: "bootstrap-datepicker",
        placeholder:"Certification Date Expired",
        class:"certification-date-expired"
      }
    }
  }
})`

**Comment by aldeed** [comment]
Closing old issues. Might be fixed in next release.
