### ISSUE TITLE
Type: String, wrong date value transformation to update form

### ISSUE THREAD

**Issue by marekhattas** [aldeed/meteor-autoform-bs-datepicker#39]
Hi,, 
if you use
{
  date: {
    type: String,
    autoform: {
      type: "bootstrap-datepicker"
    }
  }
}

Insert is OK, but when you want to use update form, the date value  in input is wrong and bad formatted to. 
If i am using type: Date, everything is OK

**Comment by aldeed** [comment]
I think next version will fix this
