### ISSUE TITLE
Month, Year Switch causes datepicker to freeze

### ISSUE THREAD

**Issue by mario589736** [aldeed/meteor-autoform-bs-datepicker#42]
I have it also in Stackoverflow:
[Month, Year Switch causes datepicker to freeze](http://stackoverflow.com/questions/36545350/meteor-aldeedautoform-bs-datepicker-month-year-switch-causes-datepicker-to-fr)

Any Ideas? Thanks!

**Comment by filipblaauw** [comment]
Same problem here

**Comment by stefanve** [comment]
Same here
DOMException: Failed to execute 'matches' on 'Element': ':visible' is not a valid selector

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
