### ISSUE TITLE
option viewMode does not seem to work

### ISSUE THREAD

**Issue by slepit** [aldeed/meteor-autoform-bs-datepicker#44]
the following setting has no effect on the view

dateNaissance: {
       type: Date,
       autoform: {
           type: "bootstrap-datepicker",
           datePickerOptions: {
               viewMode: 'years'
            }
       },
       label: 'Votre date de naissance'

**Comment by aldeed** [comment]
Closing old issues. Can be reopened if it's still an issue in the latest release.
