### ISSUE TITLE
Exception in template helper: Error: If you specify a timezoneId, make sure that you've added a moment-timezone package to your app

### ISSUE THREAD

**Issue by Netherdrake** [aldeed/meteor-autoform-bs-datepicker#47]
I get the following error:
```
Exception in template helper: Error: If you specify a timezoneId, make sure that you've added a moment-timezone package to your app
```

Despite having moment-timezone installed.

This error appears intermittently (causing datepicker to crash), I'd say about 60% of the time.

**Comment by aldeed** [comment]
The only thing that can be done here is adjusting the order your package dependencies are listed or delay your code a bit. It sounds like sometimes the `moment.tz` function just isn't done initializing by the time your form code runs.
